# Generated by Django 4.2.7 on 2023-11-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_buymessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellmessages',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuyMessage',
        ),
        migrations.DeleteModel(
            name='SellMessages',
        ),
    ]
