# Generated by Django 4.2.7 on 2023-11-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='new_password_confirm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
