# Generated by Django 4.2.7 on 2023-11-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAdvertisementDetskiymir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('expires_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
