# Generated by Django 4.2.7 on 2023-11-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'Free'), (2, 'Seven days'), (3, 'Vip')], default=1),
        ),
    ]
