# Generated by Django 4.2.7 on 2023-11-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_electroniccategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroniccategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
